[build]
builder = "nixpacks"

[build.nixpacks]
packages = ["python3", "python3-dev", "gcc", "g++", "make", "pkg-config", "gfortran", "libblas-dev", "liblapack-dev"]

[deploy]
startCommand = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"